apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "color.fullname" . }}-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.service.port }}
      name: http
      protocol: HTTP
    hosts:
    - "*"