apiVersion: v1
kind: Service
metadata:
  name: {{ include "color.fullname" . }}-svc
  labels:
    {{- include "color.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "color.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}