# Default values for color.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: 446805103418.dkr.ecr.ap-southeast-1.amazonaws.com/mini-project
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: 32Mi
    cpu: 5m

nodeSelector: {}

tolerations: []

affinity: {}

virtualService:
  route:
    - destination:
        host: istio-canary-color-svc
        subset: blue-sub
      weight: 20
    - destination:
        host: istio-canary-color-svc
        subset: green-sub
      weight: 80